:PROPERTIES:
:ID:       ced84a99-b0c9-49ca-8b4a-32d198759e71
:CAPTURED: <2022-12-06 11:12>
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SECTION: zettels
#+TITLE: WebRTC




Google has libwebrtc


- Standard ...
- Consdiered hard to use
- Linked inside of Google chrome
- 


Ericsson's OpenWebRTC

- Built on top of Gstreamer
- Was app developer centric
- 


* Key Elements

** Libnice

** Reverse Proxy technology

** 



* Direct pipeline approach


https://chromium.googlesource.com/external/webrtc/

WebRTC is a free, open software project that provides browsers and
mobile applications with Real-Time Communications (RTC) capabilities
via simple APIs. The WebRTC components have been optimized to best
serve this purpose.


* Sample running 

#+begin_src bash
webrtcbin name=webrtcbin stun-server=stun://" STUN_SERVER " \
  v4l2src device=/dev/video0 do-timestamp=true ! \
  videorate ! \
  video/x-raw,width=640,height=360,framerate=15/1 ! \
  videoconvert ! queue max-size-buffers=1 ! \
  x264enc bitrate=600 speed-preset=ultrafast tune=zerolatency key-int-max=15 ! \
  video/x-h264,profile=constrained-baseline,level=(string)4 ! \
  queue max-size-time=100000000 ! \ 
  h264parse ! \
  rtph264pay config-interval=1 name=payloader ! \
  application/x-rtp,media=video,encoding-name=H264,payload=" RTP_PAYLOAD_TYPE " ! webrtcbin.
#+end_src


#+begin_src bash
gst-launch-1.0 \
    videotestsrc pattern=ball ! \
    videoconvert ! \
    video/x-raw,format=UYVY,framerate=25/1 ! \
    jpegenc quality=75 ! \
    rtpjpegpay name=pay0 pt=26 mtu=1400 ! \
    webrtcbin name=webrtcbin stun-server=stun://192.168.8.1 
#+end_src


* Sample Setup

** Terminology

*** Client

A GStreamer-based application

*** Browser

A JS application that runs in the browser and uses built-in browser webrtc APIs

*** Peer

Any webrtc-using application that can participate in a call

*** Signalling server

Basic websockets server implemented in Python that manages the peers list and shovels data between peers

** Overview

This is a basic protocol for doing 1-1 audio+video calls between a gstreamer app and a JS app in a browser.

** Peer registration

Peers must register with the signalling server before a call can be initiated. The server connection should stay open as long as the peer is available or in a call.

This protocol builds upon https://github.com/shanet/WebRTC-Example/
:...skipping...
** Terminology

*** Client

A GStreamer-based application

*** Browser

A JS application that runs in the browser and uses built-in browser webrtc APIs

*** Peer

Any webrtc-using application that can participate in a call

*** Signalling server

Basic websockets server implemented in Python that manages the peers list and shovels data between peers

** Overview

This is a basic protocol for doing 1-1 audio+video calls between a gstreamer app and a JS app in a browser.

** Peer registration

Peers must register with the signalling server before a call can be initiated. The server connection should stay open as long as the peer is available or in a call.

This protocol builds upon https://github.com/shanet/WebRTC-Example/



** Sample from webrtc

[[https://github.com/centricular/gstwebrtc-demos/blob/master/sendrecv/gst/Dockerfile][Example docker run]]


#+begin_src bash
echo "Waiting a few seconds for you to open the browser at localhost:8080" \
    && sleep 10 \
    && ./webrtc-sendrecv \
    --peer-id=1 \
    --server=ws://signalling:8443 \
    --disable-ssl
#+end_src





* Running Single ended example

#+begin_src bash
/home/jimi_damon/Projects/work/GST/gstreamer/build/subprojects/gst-examples/webrtc/sendonly/webrtc-unidirectional-h264
WebRTC page link: http://127.0.0.1:57778/
#+end_src


Then connect to the browser and the webcamera starts forwarding images


#+begin_quote
Processing new websocket connection 0x55f1f3dc1d90Creating negotiation offer
Negotiation offer created:
v=0
o=- 18742071934976466 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:i4gAvkggmLE3NidJKt3VfDcdbHRw9laQ
a=ice-pwd:5HrLlThrYfz04zcwlhEQj3Qj3Tv243lp
a=rtcp-mux
a=rtcp-rsize
a=sendonly
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 transport-cc
a=framerate:15
a=fmtp:96 packetization-mode=1;sprop-parameter-sets=Z0LAFtoCgL/lwFqAgwMgAAADACAAAAMD0eLF1A==,aM48gA==;profile-level-id=42c016;level-asymmetry-allowed=1
a=ssrc:780714567 msid:user3541685565@host-3303ce35 webrtctransceiver0
a=ssrc:780714567 cname:user3541685565@host-3303ce35
a=mid:video0
a=fingerprint:sha-256 B5:A0:72:AD:D7:99:F0:81:8C:1C:DB:5D:40:88:BD:8C:6F:D7:53:51:85:6C:DC:3C:04:5F:A6:7F:DD:3F:74:6F
a=rtcp-mux-only
m=audio 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:3g/zAprPEwlhuyeQUbP0DKbW/wsui9Gi
a=ice-pwd:AQTLd59nyfoKXj7LhZA/lMazF3e8xwdA
a=rtcp-mux
a=rtcp-rsize
a=sendonly
a=rtpmap:97 OPUS/48000/2
a=rtcp-fb:97 transport-cc
a=fmtp:97 sprop-stereo=0;sprop-maxcapturerate=48000
a=ssrc:4272438997 msid:user3541685565@host-3303ce35 webrtctransceiver1
a=ssrc:4272438997 cname:user3541685565@host-3303ce35
a=mid:audio1
a=fingerprint:sha-256 B5:A0:72:AD:D7:99:F0:81:8C:1C:DB:5D:40:88:BD:8C:6F:D7:53:51:85:6C:DC:3C:04:5F:A6:7F:DD:3F:74:6F
a=rtcp-mux-only

Received SDP:
v=0
o=- 6489015410188880186 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:i+i7
a=ice-pwd:qONQjHEaskVQDQCilx3f9nHM
a=ice-options:trickle
a=fingerprint:sha-256 15:D4:F2:FB:89:D0:54:7E:3F:6E:17:52:A4:47:1D:04:FD:6F:61:F3:A8:2E:CE:B5:D3:F5:36:8A:00:FB:98:24
a=setup:active
a=mid:video0
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
m=audio 9 UDP/TLS/RTP/SAVPF 97
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:MxL/
a=ice-pwd:l3npbCbPjZg2P/fHnZ6JiNQA
a=ice-options:trickle
a=fingerprint:sha-256 15:D4:F2:FB:89:D0:54:7E:3F:6E:17:52:A4:47:1D:04:FD:6F:61:F3:A8:2E:CE:B5:D3:F5:36:8A:00:FB:98:24
a=setup:active
a=mid:audio1
a=recvonly
a=rtcp-mux
a=rtpmap:97 OPUS/48000/2
a=rtcp-fb:97 transport-cc
a=fmtp:97 minptime=10;useinbandfec=1
#+end_quote
